### ISSUE TITLE
Task log

### ISSUE THREAD

**Issue by stevepeak** [asyncy/ui#2]
Hi :smile: Welcome to the Λsyncy design and frontend high-level layout.

# Brand
| Name | Description |
| ---- | ---- |
| Asyncy | Main brand and product |
| Storyscript | Goal-oriented Cloud Native Programming Language |
| OMG / Open Microservice Guide | Guide to interfacing with microservices. | 

> The `OMG` **MUST** be kept seperate from Asyncy and Storyscript. It's an open standard that we just so happen to start, but the community owns it.

# Frontend

See [InVision](https://invis.io/WHMVAAINJ3G) for branding and designs.

| Site | Repo | Description |
| --- | --- | --- | 
| https://asyncy.com | [:octocat:](https://github.com/asyncy/asyncy.com) | Asyncy Home | 
| https://hub.asyncy.com | [:octocat:](https://github.com/asyncy/platform-hub) | Service discovery and marketplace. | 
| https://dashboard.asyncy.com | [:octocat:](https://github.com/asyncy/platform-dashboard) | Apps, administration and metrics. |
| https://docs.asyncy.com | [:octocat:](https://github.com/asyncy/docs.asyncy.com) | Documentation and examples | 
| https://storyscript.org | [:octocat:](https://github.com/storyscript/storyscript.org) | Documentation on Storyscript |
| https://microservice.guild | [:octocat:](https://github.com/microservices/microservice.guide) | Documentation |

### Tasks
- [ ] asyncy.com: Rebuild to RV3
- [ ] Hub: Update branding
- [ ] docs.asyncy.com: Update branding
- [ ] microservice.guide: Update branding
- [ ] Dashboard: Bootstrap
- [ ] Update asyncy/ui with new components

# Design
Submit all work to [InVision](https://invis.io/WHMVAAINJ3G) for review and archiving.

### Tasks
- [-] asyncy.com RV3 **In progress**
- [ ] Storyscript logo
- [ ] Diagram illustrations
- [ ] Design new frontend components
- [ ] Business cards
- [ ] Stickers
- [ ] Shirts
- [ ] Posters / other material
- [ ] Social media icons/backgrounds
- [ ] Email template
